### ISSUE TITLE
what's the theme and font?

### ISSUE THREAD

**Issue by caoer** [inket/update_xcode_plugins#1]
hey, thanks for the work! this has nothing to do with the repo. plz feel free to close it... :smile_cat: 

Just a question:question: . love the screenshot. what's the theme and font? is it iTerm?

:+1: :+1:

**Comment by inket** [comment]
Hi! That's fine.

You can find my Terminal setup here: https://github.com/inket/terminal-setup

Also, check the forks for that. Someone added the font and everything you need :+1:

**Comment by caoer** [comment]
@inket hey, thanks a lot, I will give it a try! :smile_cat: :smile_cat: :smile_cat:
