### ISSUE TITLE
Plug-ins still won't load

### ISSUE THREAD

**Issue by ferologics** [inket/update_xcode_plugins#13]
What could've gone wrong?

I followed all steps, tried with other methods as well, none of them work for me.

Xcode plug-ins don't load regardless of the method I use

**Comment by inket** [comment]
Maybe the plug-ins don't have the necessary compatibility UUIDs? Use the command `update_xcode_plugins` to add them.

Are you sure that you are using Xcode-unsigned.app? Also, which plug-ins are we talking about?

**Comment by ferologics** [comment]
aight, looks like the first time around it didn't add the compatibility UUIDs, now that I ran it again for some reason it detected all the plug-ins correctly - thanks :)))
