### ISSUE TITLE
Could not unsign Xcode.app

### ISSUE THREAD

**Issue by bigtreenono** [inket/update_xcode_plugins#14]
![image](https://cloud.githubusercontent.com/assets/8012469/18805605/de4d3d56-8244-11e6-8350-d732d71a66fa.png)

**Comment by inket** [comment]
1. It could be a permissions issue, the easiest way to check is to use `sudo`:
  - `sudo update_xcode_plugins --unsafe-unsign`
2. If the error shows up again, `Xcode.app` might be protected by *[System Integrity Protection](https://en.wikipedia.org/wiki/System_Integrity_Protection)* (haven't verified myself when implementing that feature as I have SIP disabled on my system)
  - You can disable SIP [this way](http://www.macworld.com/article/2986118/security/how-to-modify-system-integrity-protection-in-el-capitan.html) or just use `--unsign` instead

Can you confirm?

**Comment by bigtreenono** [comment]
The first one works, thank you.
