### ISSUE TITLE
Operation not permitted - /usr/bin/term_cdiff

### ISSUE THREAD

**Issue by saber1024** [inket/update_xcode_plugins#16]
i try this 
Saber@SaberdeMacBook-Pro ~$ sudo gem install update_xcode_plugins
Password:
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/term_cdiff

**Comment by inket** [comment]
Might be the same issue as #10 

Can you try this?
```bash
sudo gem install -n /usr/local/bin update_xcode_plugins
```

**Comment by inket** [comment]
Closing this for lack of response.
