### ISSUE TITLE
Why remove the signature will be able to load the plug-in, this is what the principle? 

### ISSUE THREAD

**Issue by ShengQiangLiu** [inket/update_xcode_plugins#17]
Why remove the signature will be able to load the plug-in, this is what the principle? After removing the signature, Xcode can also be packaged App AppStore shelves?

**Comment by inket** [comment]
1. These resources should help:
- http://stackoverflow.com/questions/37878401/will-xcode-8-support-plugins-alcatraz/38814459#38814459
- https://github.com/inket/update_xcode_plugins/blob/master/README.md
- https://github.com/alcatraz/Alcatraz/issues/475

2. Probably.
