### ISSUE TITLE
spctl not invalid

### ISSUE THREAD

**Issue by BaiTianyu** [inket/update_xcode_plugins#19]
After I uninstall update_xcode_plugins and the Xcode-unsigned.app(the copy). The original Xcode.app cause the error "/Applications/Xcode.app: a sealed resource is missing or invalid" when I apply spctl --assess --verbose /Applications/Xcode.app . I want know why, does update_xcode_plugin do something on my original Xcode?

**Comment by inket** [comment]
Nope!

The **only** case where `update_xcode_plugins` changes the original Xcode is if you use `update_xcode_plugins --unsafe-unsign`

**Comment by inket** [comment]
Please create a new issue if you can link this error to `update_xcode_plugins`.
