### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by dev4dev** [inket/update_xcode_plugins#20]
Xcode 8.1

update_xcode_plugins --unsafe-unsign
Unsigning...
/Applications/Xcode.app/Contents/MacOS/Xcode.unsigned: Permission denied
Could not unsign Xcode.app

**Comment by inket** [comment]
Please check https://github.com/inket/update_xcode_plugins/issues/14#issuecomment-249346367

Thank you

**Comment by dev4dev** [comment]
I've tried that, but now my rvm setup can't handle it. Will try to do something. Thanks

**Comment by inket** [comment]
I'm curious, please share your rvm error message if you can. Also, if you find any solution! Thanks

**Comment by dev4dev** [comment]
Solution is simple `sudo gem install update_xcode_plugins` =)
