### ISSUE TITLE
Didn't find any Xcode 8+ installed on your system

### ISSUE THREAD

**Issue by liuyuzhe** [inket/update_xcode_plugins#22]
In Xcode 8.1:
update_xcode_plugins --unsafe-unsign
Looking for Xcode...

Didn't find any Xcode 8+ installed on your system.

**Comment by inket** [comment]
Is Xcode at `/Applications/Xcode.app`?

If not, enable Spotlight indexation so it can be found.

**Comment by liuyuzhe** [comment]
yes, I'm sure Xcode at /Applications/Xcode.app. 
The problem still exists.

**Comment by inket** [comment]
If your Xcode is already unsigned it will not be found because `update_xcode_plugins --unsafe-unsign` ignores unsigned Xcodes.

Sorry for the confusion. I guess I should make it clearer in the next version.
