### ISSUE TITLE
Does it work with Xcode 8.1?

### ISSUE THREAD

**Issue by inket** [inket/update_xcode_plugins#25]
@Marviszhao

From https://github.com/inket/update_xcode_plugins/issues/23#issuecomment-257499941
> Does is support xcode8.1 ? I update my original xcode to 8.1 and update_xcode_plugins success.but my plugins can not be use .it was ok on xcode 8.0

Yes, this supports Xcode 8.1 (tested on my system)

If you updated the original `Xcode.app` to 8.1, delete `Xcode-unsigned.app` then run `update_xcode_plugins` and `update_xcode_plugins --unsign` again. Plugins should work then.

If the plugin is still not working, said plugin may not be compatible with Xcode 8.1, in which case you have to contact the plugin's developer.

Does this answer your question?

**Comment by lizhaojie001** [comment]
![353ce2c6-76a1-418f-8c87-8ac2cd209948](https://cloud.githubusercontent.com/assets/14847521/20163605/c4abe24e-a738-11e6-9a5e-f0f511ebf496.png)
