### ISSUE TITLE
Xcode-unsigned.app not finding simulators

### ISSUE THREAD

**Issue by DarthMike** [inket/update_xcode_plugins#30]
Hi, thanks for a great utility!

After latest upgrade to Xcode 8.1, on my system, the simulators are not discovered from `Xcode-unsigned.app` but are discovered from original `Xcode.app`.

I had this issue for a couple of days but then decided to rename `Xcode-unsigned.app` to `Xcode.app`, and the original `Xcode.app` to `Xcode-signed.app`. Then simulators appear again in my unsigned copy.

Do you think the tool could be changed so it renames the original Xcode before copying, instead of renaming the unsigned one?

Thanks!

**Comment by inket** [comment]
Thank you for reporting this issue! I will have a fix for it soon.

**Comment by inket** [comment]
Hi again! Can you try the new version? It should unsign Xcode without creating a copy, which shouldn't cause any problems. (can be restored with the new `--restore` command)

**Comment by DarthMike** [comment]
Thanks! I'll try later today.

**Comment by DarthMike** [comment]
Thanks @inket now works perfectly. Noticed you've added `restore` option, so saving disk space ;)
