### ISSUE TITLE
not working with Xcode 8.2.1

### ISSUE THREAD

**Issue by woshishuxiong** [inket/update_xcode_plugins#33]
Xcode 8.1 is ok.

**Comment by inket** [comment]
How? Did you get an error? Can you describe what happened? "not working" is not helpful.

**Comment by woshishuxiong** [comment]
So sorry. I unsigned my Xcode8.2.1 and update my Xvim plugin like before in Xcode8.1. But I found no Xvim in the editor Menu when it was done. So I think it does not work in 8.2.1. There was no error in the console.

**Comment by inket** [comment]
I just compiled XVim and I can confirm that it works with Xcode 8.2.1 unsigned via update_xcode_plugins:

![screen shot 2017-01-03 at 9 33 05 p](https://cloud.githubusercontent.com/assets/679224/21607877/6e37bc78-d1fc-11e6-9ee3-d7a0da5e74e0.png)
<img width="532" alt="screen shot 2017-01-03 at 9 32 30 p" src="https://cloud.githubusercontent.com/assets/679224/21607878/717ad74e-d1fc-11e6-9baf-aac9698b62ec.png">
<img width="334" alt="screen shot 2017-01-03 at 9 32 44 p" src="https://cloud.githubusercontent.com/assets/679224/21607880/73f2ad94-d1fc-11e6-9db5-39a38b58138f.png">

Something is not right in your setup and I suggest these solutions:

- Run `update_xcode_plugins --unsign`. If your Xcode is already unsigned, the output should be 
<img width="347" alt="screen shot 2017-01-03 at 9 38 52 p" src="https://cloud.githubusercontent.com/assets/679224/21607992/0d361aa4-d1fd-11e6-92da-9aea3ee7c38d.png">

- Run `update_xcode_plugins` to update plugin UUIDs to get it to load

- Run `defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-8.2.1` then start Xcode and click "Load Bundles" when asked

<img width="532" alt="screen shot 2017-01-03 at 9 32 30 p" src="https://cloud.githubusercontent.com/assets/679224/21607878/717ad74e-d1fc-11e6-9baf-aac9698b62ec.png">

**Comment by woshishuxiong** [comment]
It's ok now. Maybe I did not run this before, "defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-8.2.1"..Thanks..very grateful.
