### ISSUE TITLE
how should i use it?

### ISSUE THREAD

**Issue by KKKiller** [inket/update_xcode_plugins#40]
![1](https://user-images.githubusercontent.com/12382253/28702221-2e3487d0-738e-11e7-8a32-aec086c5710a.png)
<img width="342" alt="2" src="https://user-images.githubusercontent.com/12382253/28702246-563de1e0-738e-11e7-97bb-66cf92f16833.png">
xcode 8.3.3
did i install success?
how should i use it?
thanks!!

**Comment by inket** [comment]
Yes - it seems you successfully unsigned Xcode.

However, you do not have any plugins to load...
- Find some plugins you're interested in using, like [Alcatraz](https://github.com/alcatraz/Alcatraz)
- Install them
- Run `update_xcode_plugins`

**Comment by inket** [comment]
I assume this has been resolved since there were no further replies.
