### ISSUE TITLE
When unsigned Xcode 9 can't create new project

### ISSUE THREAD

**Issue by cuzv** [inket/update_xcode_plugins#43]
will stopped when click 'next' button for create new project;

**Comment by cuzv** [comment]
Turns out it is quite same issues like #23 #25.
My solution is disable every single one access authority for Xcode in privacy settings.
Then launch Xcode and select privacy settings back.

**Comment by inket** [comment]
Glad you could get it resolved. I was going to mention the other issues. Thanks for sharing the fix!

**Comment by cuzv** [comment]
Thx for the awesome tools.
