### ISSUE TITLE
When will Xcode 9.4 be supported?

### ISSUE THREAD

**Issue by GanZhiXiong** [inket/update_xcode_plugins#50]

**Comment by inket** [comment]
It's probably already supported so you can use it fine. I will add the tests and update the README this week.

**Comment by inket** [comment]
I confirmed that it works on my machine. I cannot add the test for that version though, since travis-ci doesn't support it yet.

**Comment by GanZhiXiong** [comment]
OK.Thank you very much for your reply. I will test again
